substitutions:
  _LOCATION: us-central1
  _REPOSITORY: visions-cloud-run
  _SERVICE_NAME: visions-cloud-run

steps:
  # 1. Install dependencies and run tests
  - name: 'python:3.10'
    id: Test
    entrypoint: bash
    args:
    - -c
    - |
        pip install -r requirements.txt
        python -m unittest test_main.py

  # 2. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '.'
    waitFor:
      - Test

  # 3. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
    waitFor:
      - Build

  # 4. Deploy to Cloud Run using the service.yaml configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        # Substitute the static image placeholder in service.yaml with the dynamic image built in the previous steps.
        sed -i "s|image: gcr.io/sandbox-456821/visions-cloud-run|image: ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}|" service.yaml
        
        # Deploy the service using the updated configuration file.
        gcloud run services replace service.yaml --region ${_LOCATION}
    waitFor:
      - Push

options:
  logging: CLOUD_LOGGING_ONLY
