apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: visions-cloud-run
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    spec:
      containers:
      - image: gcr.io/sandbox-456821/visions-cloud-run
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        env:
        - name: REASONING_ENGINE_NAME
          value: "projects/sandbox-456821/locations/us-central1/reasoningEngines/1352192593978458112"
